server:
   port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        #server-addr: 123.57.180.198:8848 #配置Nacos地址
        # 换成nginx的6601端口，做集群
        server-addr: 123.57.180.198:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
#          lower-case-service-id: true
      routes:
        - id: payment_routh #payment_route    # 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
#            - After=2021-02-21T15:51:37.485+08:00[Asia/Shanghai]
#            - Before=2021-02-21T15:51:37.485+08:00[Asia/Shanghai]
#            - Between=2020-02-21T15:51:37.485+08:00[Asia/Shanghai],2021-02-21T15:51:37.485+08:00[Asia/Shanghai]
#            - Cookie=username,ywj
#            - Header=X-Request-Id, \d+   # 请求头要有 X-Request-Id 属性并且值为整数的正则表达式
#          filters:
#            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id 值为1024
        - id: user_routh
          uri: lb://user-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/user/**         # 断言，路径相匹配的进行路由
        - id: menu_routh
          uri: lb://menu-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/menu/**         # 断言，路径相匹配的进行路由
        - id: role_routh
          uri: lb://role-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/role/**         # 断言，路径相匹配的进行路由
        - id: task_routh
          uri: lb://task-service  # 匹配后提供服务的路由地址
          predicates:
              - Path=/task/**         # 断言，路径相匹配的进行路由
#      enabled: true
#      api-prefix: /api/v1


  main:
    allow-bean-definition-overriding: true
newtranx:
  account:
    domainname: http://221.122.93.231
#    domainname: https://accounts.newtranx.com
    client_id: 29d01a73b30d43c8980a4e08f934f96a
    client_secret: Q1GBaEGNxFs99cnQbY1n9kbejRS5pTmF
    token_status: /api/v1/oauth2/token-status


