server:
  port: 9204
  servlet:
    context-path: /cat

spring:
  application:
    name: cat-service
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.180.198:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.57.180.198:3306/cloud_edit?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: cloud_edit
    password: xykj2015
  data:
    mongodb:
#      uri: mongodb://127.0.0.1:27017/cat
      uri: mongodb://admin:pass%40123!@123.57.180.198:27017/cat?authSource=admin&authMechanism=SCRAM-SHA-1

  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.newtranx.cloud.edit.entities
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  compression:
    request:
      min-request-size: 20480000
#auth:
#  service: auth-service
#
#security:
#  oauth2:
#    resource:
#      jwt:
#        key-uri: http://localhost:7002/oauth/token_key
#    client:
#      client-id: client_3
#      client-secret: 123456
#      access-token-uri: http://localhost:7002/oauth/token
#      grant-type: password
#      scope: edit
#      user-authorization-uri: http://localhost:7002/oauth/authorize