server:
  port: 7004
  servlet:
    context-path: /menu

spring:
  application:
    name: menu-service
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.180.198:8848
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.57.180.198:3306/cloud_edit?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: cloud_edit
    password: xykj2015


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.newtranx.cloud.edit.entities
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

auth:
  service: auth-service

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:7002/oauth/token_key
    client:
      client-id: client_3
      client-secret: 123456
      access-token-uri: http://localhost:7002/oauth/token
      grant-type: password
      scope: edit
      user-authorization-uri: http://localhost:7002/oauth/authorize

